### ISSUE TITLE
Presenting HiveOT in a W3C WoT Community Group Meetup

### ISSUE THREAD

**Issue by egekorkan** [hiveot/hub#13]
Hi @hspaay ! The [W3C WoT Community Group](https://www.w3.org/community/wot/) organizes meetups where adopters of WoT can present their solutions. Given that HiveOT uses WoT, would you be interested in presenting it? If so, we can arrange presentation slot etc. via email (or here maybe?). You can contact me at `ege.korkan at siemens.com`

**Comment by hspaay** [comment]
Hello Ege, Thanks for checking out HiveOT. I'll followup via email.
